export const data = [
    { continent: "America", country: "United States of America", value: 916.01, code: "USA" },
    { continent: "Asia", country: "China", value: 296.44, code: "CN" },
    { continent: "Europe", country: "Russia", value: 109.45, code: "RU" },
    { continent: "Asia", country: "India", value: 83.57, code: "IN" },
    { continent: "Asia", country: "Saudi Arabia", value: 75.81, code: "SA" },
    { continent: "Europe", country: "United Kingdom", value: 74.94, code: "UK" },
    { continent: "Europe", country: "Germany", value: 66.83, code: "DE" },
    { continent: "Europe", country: "Ukraine", value: 64.75, code: "UA" },
    { continent: "Europe", country: "France", value: 61.30, code: "FR" },
    { continent: "Asia", country: "Japan", value: 50.16, code: "JP" },
    { continent: "Asia", country: "Korea, South", value: 47.93, code: "KR" },
    { continent: "Europe", country: "Italy", value: 35.53, code: "IT" },
    { continent: "Oceania", country: "Australia", value: 32.34, code: "AU" },
    { continent: "Europe", country: "Poland", value: 31.65, code: "PL" },
    { continent: "Asia", country: "Israel", value: 27.50, code: "IL" },
    { continent: "America", country: "Canada", value: 27.22, code: "CA" },
    { continent: "Europe", country: "Spain", value: 23.70, code: "ES" },
    { continent: "America", country: "Brazil", value: 22.89, code: "BR" },
    { continent: "Africa", country: "Algeria", value: 18.26, code: "DZ" },
    { continent: "Europe", country: "Netherlands", value: 16.62, code: "NL" },
    { continent: "Asia", country: "Taiwan", value: 16.61, code: "TW" },
    { continent: "Asia", country: "Türkiye", value: 15.83, code: "TR" },
    { continent: "Asia", country: "Singapore", value: 13.20, code: "SG" },
    { continent: "America", country: "Mexico", value: 11.83, code: "MX" },
    { continent: "America", country: "Colombia", value: 10.70, code: "CO" },
    { continent: "Asia", country: "Iran", value: 10.28, code: "IR" },
    { continent: "Asia", country: "Indonesia", value: 9.48, code: "ID" },
    { continent: "Europe", country: "Sweden", value: 8.75, code: "SE" },
    { continent: "Europe", country: "Norway", value: 8.67, code: "NO" },
    { continent: "Asia", country: "Pakistan", value: 8.52, code: "PK" },
    { continent: "Europe", country: "Denmark", value: 8.14, code: "DK" },
    { continent: "Asia", country: "Kuwait", value: 7.76, code: "KW" },
    { continent: "Europe", country: "Greece", value: 7.73, code: "GR" },
    { continent: "Europe", country: "Belgium", value: 7.63, code: "BE" },
    { continent: "Europe", country: "Finland", value: 7.35, code: "FI" },
    { continent: "Europe", country: "Switzerland", value: 6.29, code: "CH" },
    { continent: "Asia", country: "Oman", value: 5.85, code: "OM" },
    { continent: "Asia", country: "Thailand", value: 5.77, code: "TH" },
    { continent: "Europe", country: "Romania", value: 5.61, code: "RO" },
    { continent: "America", country: "Chile", value: 5.49, code: "CL" },
    { continent: "Asia", country: "Philippines", value: 5.45, code: "PH" },
    { continent: "Africa", country: "Morocco", value: 5.18, code: "MA" },
    { continent: "Asia", country: "Iraq", value: 5.11, code: "IQ" },
    { continent: "Europe", country: "Czechia", value: 5.06, code: "CZ" },
    { continent: "Europe", country: "Austria", value: 4.41, code: "AT" },
    { continent: "Europe", country: "Hungary", value: 4.36, code: "HU" },
    { continent: "Europe", country: "Portugal", value: 4.22, code: "PT" },
    { continent: "Asia", country: "Bangladesh", value: 4.21, code: "BD" },
    { continent: "Asia", country: "Malaysia", value: 3.90, code: "MY" },
    { continent: "Asia", country: "Azerbaijan", value: 3.56, code: "AZ" },
];
