export const data = [
  { country: "Latvia", male: 7.1, female: 9.5 },
  { country: "Finland", male: 7.7, female: 9.4 },
  { country: "Estonia", male: 7.9, female: 9.1 },
  { country: "Poland", male: 3.4, female: 4.2 },
  { country: "Ireland", male: 2.5, female: 3.4 },
  { country: "Denmark", male: 2.8, female: 3.3 },
  { country: "Slovenia", male: 3.4, female: 3.3 },
  { country: "Portugal", male: 2.0, female: 2.9 },
  { country: "Romania", male: 1.6, female: 2.8 },
  { country: "Sweden", male: 1.9, female: 2.5 },
  { country: "Italy", male: 1.4, female: 2.4 },
  { country: "Spain", male: 1.6, female: 2.0 },
  { country: "Croatia", male: 0.9, female: 1.7 },
  { country: "Norway", male: 1.6, female: 1.7 },
  { country: "Belgium", male: 1.2, female: 1.5 },
  { country: "Bulgaria", male: 0.9, female: 1.3 },
  { country: "Türkiye", male: 1.0, female: 1.3 },
  { country: "Luxembourg", male: 0.9, female: 1.1 },
  { country: "Hungary", male: 0.9, female: 1.1 },
  { country: "Germany", male: 0.7, female: 0.9 },
  { country: "Netherlands", male: 0.4, female: 0.8 },
  { country: "Czechia", male: 0.4, female: 0.5 },
  { country: "Cyprus", male: 0.1, female: 0.1 },
];
