export const data = [
  {
    temporada: "24/25",
    campeon: "",
    barcelona: 91,
    madrid: 86,
    r_barcelona: 67,
    r_madrid: 63,
  },
  {
    temporada: "23/24",
    campeon: "Real Madrid",
    barcelona: 85,
    madrid: 95,
    r_barcelona: 85,
    r_madrid: 95,
  },
  {
    temporada: "22/23",
    campeon: "Barcelona",
    barcelona: 88,
    madrid: 78,
    r_barcelona: 88,
    r_madrid: 78,
  },
  {
    temporada: "21/22",
    campeon: "Real Madrid",
    barcelona: 73,
    madrid: 86,
    r_barcelona: 73,
    r_madrid: 86,
  },
  {
    temporada: "20/21",
    campeon: "Atlético de Madrid",
    barcelona: 79,
    madrid: 84,
    r_barcelona: 79,
    r_madrid: 84,
  },
  {
    temporada: "19/20",
    campeon: "Real Madrid",
    barcelona: 82,
    madrid: 87,
    r_barcelona: 82,
    r_madrid: 87,
  },
  {
    temporada: "18/19",
    campeon: "Barcelona",
    barcelona: 87,
    madrid: 68,
    r_barcelona: 87,
    r_madrid: 68,
  },
  {
    temporada: "17/18",
    campeon: "Barcelona",
    barcelona: 93,
    madrid: 76,
    r_barcelona: 93,
    r_madrid: 76,
  },
  {
    temporada: "16/17",
    campeon: "Real Madrid",
    barcelona: 90,
    madrid: 93,
    r_barcelona: 90,
    r_madrid: 93,
  },
  {
    temporada: "15/16",
    campeon: "Barcelona",
    barcelona: 91,
    madrid: 90,
    r_barcelona: 91,
    r_madrid: 90,
  },
  {
    temporada: "14/15",
    campeon: "Barcelona",
    barcelona: 94,
    madrid: 92,
    r_barcelona: 94,
    r_madrid: 92,
  },
  {
    temporada: "13/14",
    campeon: "Atlético de Madrid",
    barcelona: 87,
    madrid: 87,
    r_barcelona: 87,
    r_madrid: 87,
  },
  {
    temporada: "12/13",
    campeon: "Barcelona",
    barcelona: 100,
    madrid: 85,
    r_barcelona: 100,
    r_madrid: 85,
  },
  {
    temporada: "11/12",
    campeon: "Real Madrid",
    barcelona: 91,
    madrid: 100,
    r_barcelona: 91,
    r_madrid: 100,
  },
  {
    temporada: "10/11",
    campeon: "Barcelona",
    barcelona: 96,
    madrid: 92,
    r_barcelona: 96,
    r_madrid: 92,
  },
  {
    temporada: "09/10",
    campeon: "Barcelona",
    barcelona: 99,
    madrid: 96,
    r_barcelona: 99,
    r_madrid: 96,
  },
  {
    temporada: "08/09",
    campeon: "Barcelona",
    barcelona: 87,
    madrid: 78,
    r_barcelona: 87,
    r_madrid: 78,
  },
  {
    temporada: "07/08",
    campeon: "Real Madrid",
    barcelona: 67,
    madrid: 85,
    r_barcelona: 67,
    r_madrid: 85,
  },
  {
    temporada: "06/07",
    campeon: "Real Madrid",
    barcelona: 76,
    madrid: 76,
    r_barcelona: 76,
    r_madrid: 76,
  },
  {
    temporada: "05/06",
    campeon: "Barcelona",
    barcelona: 82,
    madrid: 70,
    r_barcelona: 82,
    r_madrid: 70,
  },
  {
    temporada: "04/05",
    campeon: "Barcelona",
    barcelona: 84,
    madrid: 80,
    r_barcelona: 84,
    r_madrid: 80,
  },
  {
    temporada: "03/04",
    campeon: "Valencia CF",
    barcelona: 72,
    madrid: 70,
    r_barcelona: 72,
    r_madrid: 70,
  },
  {
    temporada: "02/03",
    campeon: "Real Madrid",
    barcelona: 61,
    madrid: 78,
    r_barcelona: 61,
    r_madrid: 78,
  },
  {
    temporada: "01/02",
    campeon: "Valencia CF",
    barcelona: 64,
    madrid: 66,
    r_barcelona: 64,
    r_madrid: 66,
  },
  {
    temporada: "00/01",
    campeon: "Real Madrid",
    barcelona: 69,
    madrid: 80,
    r_barcelona: 69,
    r_madrid: 80,
  }
]
