export const data = {
    nodes: [
        { id: "1", name: "Data", size: 20, group: 1 },
        { id: "2", name: "Data visualization", size: 15, group: 1 },
        { id: "3", name: "Data analysis", size: 10, group: 2 },
        { id: "4", name: "Data cleaning", size: 8, group: 2 },
        { id: "5", name: "Machine Learning", size: 14, group: 3 },
        { id: "6", name: "Deep Learning", size: 10, group: 3 },
        { id: "7", name: "Big Data", size: 14, group: 4 },
        { id: "8", name: "Cloud Computing", size: 14, group: 4 },
        { id: "9", name: "Data Wrangling", size: 10, group: 1 },
        { id: "10", name: "Exploratory Analysis", size: 14, group: 2 },
        { id: "11", name: "Predictive Modeling", size: 14, group: 3 },
        { id: "12", name: "Data Pipelines", size: 10, group: 4 },
        { id: "13", name: "Data Ethics", size: 14, group: 5 },
        { id: "14", name: "Data Governance", size: 15, group: 5 },
        { id: "15", name: "Data Security", size: 10, group: 5 },
        { id: "16", name: "Data Privacy", size: 14, group: 5 },
        { id: "17", name: "Data Integration", size: 10, group: 5 },
        { id: "18", name: "Data Reporting", size: 14, group: 1 },
        { id: "19", name: "Data Sampling", size: 8, group: 2 },
        { id: "20", name: "D3", size: 10, group: 3 },
        { id: "21", name: "Data Quality", size: 6, group: 6 },
        { id: "22", name: "Data Transformation", size: 6, group: 6 },
        { id: "23", name: "Data Aggregation", size: 6, group: 6 },
        { id: "24", name: "Data Storage", size: 6, group: 6 },
        { id: "25", name: "Data Retrieval", size: 6, group: 6 },
        { id: "26", name: "Data Formats", size: 6, group: 6 },
        { id: "27", name: "Data APIs", size: 6, group: 6 },
        { id: "28", name: "Data Workflows", size: 6, group: 6 },
        { id: "29", name: "Data Tools", size: 6, group: 6 },
        { id: "30", name: "Data Libraries", size: 6, group: 6 },
        { id: "31", name: "Scrollytelling", size: 6, group: 6 },
        { id: "32", name: "Automation", size: 6, group: 6 },
        { id: "33", name: "Metrics", size: 6, group: 6 },
        { id: "34", name: "Benchmarks", size: 6, group: 6 },
        { id: "35", name: "Trends", size: 6, group: 6 },
        { id: "36", name: "Insights", size: 6, group: 6 },
        { id: "37", name: "Dashboards", size: 6, group: 6 },
        { id: "38", name: "Charts", size: 6, group: 6 },
        { id: "39", name: "Maps", size: 6, group: 6 },
        { id: "40", name: "Stories", size: 6, group: 6 }
    ],
    links: [
        { source: "1", target: "2" },
        { source: "1", target: "3" },
        { source: "2", target: "4" },
        { source: "3", target: "5" },
        { source: "4", target: "6" },
        { source: "5", target: "7" },
        { source: "6", target: "8" },
        { source: "7", target: "1" },
        { source: "9", target: "1" },
        { source: "9", target: "2" },
        { source: "10", target: "3" },
        { source: "10", target: "4" },
        { source: "11", target: "5" },
        { source: "11", target: "6" },
        { source: "12", target: "7" },
        { source: "12", target: "8" },
        { source: "13", target: "14" },
        { source: "13", target: "15" },
        { source: "14", target: "16" },
        { source: "15", target: "17" },
        { source: "16", target: "18" },
        { source: "17", target: "19" },
        { source: "18", target: "20" },
        { source: "19", target: "1" },
        { source: "20", target: "2" },
        { source: "13", target: "1" },
        { source: "14", target: "3" },
        { source: "15", target: "5" },
        { source: "16", target: "7" },
        { source: "17", target: "9" },
        { source: "21", target: "20" },
        { source: "22", target: "20" },
        { source: "23", target: "20" },
        { source: "24", target: "16" },
        { source: "25", target: "16" },
        { source: "26", target: "16" },
        { source: "27", target: "14" },
        { source: "28", target: "13" },
        { source: "29", target: "12" },
        { source: "30", target: "11" },
        { source: "31", target: "10" },
        { source: "32", target: "10" },
        { source: "33", target: "18" },
        { source: "34", target: "18" },
        { source: "35", target: "9" },
        { source: "36", target: "9" },
        { source: "37", target: "8" },
        { source: "38", target: "8" },
        { source: "39", target: "7" },
        { source: "40", target: "7" }
    ]
};
