export const data = [
    { state: "Alaska", abbr: "AK", row: 1, col: 0, killed: 14, injured: 3, shootings: 2 },
    { state: "Arizona", abbr: "AZ", row: 6, col: 1, killed: 15, injured: 15, shootings: 3 },
    { state: "California", abbr: "CA", row: 5, col: 0, killed: 235, injured: 246, shootings: 32 },
    { state: "Colorado", abbr: "CO", row: 5, col: 2, killed: 76, injured: 180, shootings: 10 },
    { state: "Hawaii", abbr: "HI", row: 8, col: 0, killed: 7, injured: 0, shootings: 1 },
    { state: "Idaho", abbr: "ID", row: 3, col: 1, killed: 4, injured: 0, shootings: 1 },
    { state: "Illinois", abbr: "IL", row: 4, col: 5, killed: 31, injured: 85, shootings: 8 },
    { state: "Indiana", abbr: "IN", row: 4, col: 6, killed: 12, injured: 12, shootings: 2 },
    { state: "Iowa", abbr: "IA", row: 4, col: 4 },
    { state: "Kansas", abbr: "KS", row: 6, col: 3, killed: 13, injured: 12, shootings: 3 },
    { state: "Maine", abbr: "ME", row: 1, col: 10, killed: 18, injured: 13, shootings: 1 },
    { state: "Michigan", abbr: "MI", row: 3, col: 6, killed: 25, injured: 17, shootings: 5 },
    { state: "Minnesota", abbr: "MN", row: 3, col: 4, killed: 15, injured: 9, shootings: 2 },
    { state: "Missouri", abbr: "MO", row: 5, col: 4, killed: 10, injured: 4, shootings: 2 },
    { state: "Montana", abbr: "MT", row: 3, col: 2 },
    { state: "Nebraska", abbr: "NE", row: 5, col: 3, killed: 8, injured: 5, shootings: 1 },
    { state: "Nevada", abbr: "NV", row: 4, col: 1, killed: 64, injured: 868, shootings: 3 },
    { state: "New Hampshire", abbr: "NH", row: 2, col: 9, killed: 4, injured: 4, shootings: 1 },
    { state: "New Mexico", abbr: "NM", row: 6, col: 2 },
    { state: "North Dakota", abbr: "ND", row: 3, col: 3 },
    { state: "Ohio", abbr: "OH", row: 4, col: 7, killed: 20, injured: 30, shootings: 2 },
    { state: "Oklahoma", abbr: "OK", row: 7, col: 3, killed: 18, injured: 6, shootings: 2 },
    { state: "Oregon", abbr: "OR", row: 4, col: 0, killed: 19, injured: 55, shootings: 3 },
    { state: "South Dakota", abbr: "SD", row: 4, col: 3 },
    { state: "Utah", abbr: "UT", row: 5, col: 1, killed: 5, injured: 4, shootings: 1 },
    { state: "Vermont", abbr: "VT", row: 2, col: 8 },
    { state: "Washington", abbr: "WA", row: 3, col: 0, killed: 25, injured: 33, shootings: 8 },
    { state: "Wisconsin", abbr: "WI", row: 3, col: 5, killed: 34, injured: 13, shootings: 6 },
    { state: "Wyoming", abbr: "WY", row: 4, col: 2 },
    { state: "Alabama", abbr: "AL", row: 7, col: 5, killed: 4, injured: 1, shootings: 1 },
    { state: "Arkansas", abbr: "AR", row: 6, col: 4, killed: 19, injured: 31, shootings: 5 },
    { state: "Connecticut", abbr: "CT", row: 3, col: 9, killed: 35, injured: 3, shootings: 3 },
    { state: "Delaware", abbr: "DE", row: 5, col: 8 },
    { state: "Florida", abbr: "FL", row: 8, col: 8, killed: 165, injured: 163, shootings: 15 },
    { state: "Georgia", abbr: "GA", row: 7, col: 6, killed: 28, injured: 29, shootings: 6 },
    { state: "Kentucky", abbr: "KY", row: 5, col: 5, killed: 32, injured: 33, shootings: 6 },
    { state: "Louisiana", abbr: "LA", row: 7, col: 4, killed: 16, injured: 21, shootings: 3 },
    { state: "Maryland", abbr: "MD", row: 5, col: 7, killed: 5, injured: 3, shootings: 1 },
    { state: "Massachusetts", abbr: "MA", row: 2, col: 10, killed: 7, injured: 0, shootings: 1 },
    { state: "Mississippi", abbr: "MS", row: 6, col: 5, killed: 15, injured: 11, shootings: 3 },
    { state: "New Jersey", abbr: "NJ", row: 4, col: 9, killed: 26, injured: 9, shootings: 6 },
    { state: "New York", abbr: "NY", row: 3, col: 8, killed: 38, injured: 34, shootings: 10 },
    { state: "North Carolina", abbr: "NC", row: 6, col: 8, killed: 31, injured: 18, shootings: 8 },
    { state: "Pennsylvania", abbr: "PA", row: 4, col: 8, killed: 36, injured: 37, shootings: 10 },
    { state: "Rhode Island", abbr: "RI", row: 3, col: 10, killed: 4, injured: 0, shootings: 1 },
    { state: "South Carolina", abbr: "SC", row: 7, col: 7, killed: 13, injured: 4, shootings: 2 },
    { state: "Tennessee", abbr: "TN", row: 6, col: 6, killed: 15, injured: 6, shootings: 3 },
    { state: "Texas", abbr: "TX", row: 8, col: 3, killed: 215, injured: 212, shootings: 26 },
    { state: "Virginia", abbr: "VA", row: 6, col: 7, killed: 50, injured: 36, shootings: 4 },
    { state: "West Virginia", abbr: "WV", row: 5, col: 6 },
];
